"""Resumable, paced downloads of transcript lists."""

from __future__ import annotations

import json
import os
import tempfile
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable
from urllib.parse import quote

from videocontext.extractors.transcript import RateLimitedError, TranscriptSegment, fetch_transcript
from videocontext.extractors.transcript import _is_rate_limited
from videocontext.url import extract_video_id


CATALOG_MARKER = "<!-- Generated by VideoContext; edit the title inventory instead. -->"


@dataclass(frozen=True)
class BatchStatus:
    total: int
    saved: int
    pending: int


@dataclass(frozen=True)
class BatchSummary:
    total: int
    completed: int
    skipped: int
    failed: int
    rate_limit_retries: int


class BatchPaused(RuntimeError):
    """A rate limit persisted after the configured number of retries."""

    def __init__(self, video_id: str, retries: int, summary: BatchSummary):
        super().__init__(f"Rate limit persisted for {video_id} after {retries} retries; resume later.")
        self.video_id = video_id
        self.retries = retries
        self.summary = summary


def _load_video_ids(ids_file: Path) -> list[str]:
    videos: list[str] = []
    seen: set[str] = set()
    for number, raw in enumerate(ids_file.read_text(encoding="utf-8").splitlines(), start=1):
        value = raw.strip()
        if not value or value.startswith("#"):
            continue
        try:
            video_id = extract_video_id(value)
        except ValueError as error:
            raise ValueError(f"Invalid video at line {number}: {error}") from error
        if video_id not in seen:
            videos.append(video_id)
            seen.add(video_id)
    return videos


def _load_index(output_dir: Path) -> dict[str, dict[str, str]]:
    path = output_dir / "metadata" / "batch_index.json"
    if not path.exists():
        path = output_dir / "_batch_index.json"
    if not path.exists():
        return {}
    index = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(index, dict):
        raise ValueError(f"Invalid transcript index: {path}")
    for video_id, entry in index.items():
        if not isinstance(video_id, str) or not isinstance(entry, dict):
            raise ValueError(f"Invalid transcript index entry in {path}")
        filename = entry.get("filename")
        if not isinstance(filename, str) or Path(filename).is_absolute() or ".." in Path(filename).parts:
            raise ValueError(f"Unsafe transcript filename in {path}: {video_id}")
    return index


def _save_index(output_dir: Path, index: dict[str, dict[str, str]]) -> None:
    directory = output_dir / "metadata"
    directory.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=directory,
            prefix=".batch_index.", suffix=".tmp", delete=False,
        ) as handle:
            temporary = Path(handle.name)
            json.dump(index, handle, ensure_ascii=False, indent=2)
            handle.write("\n")
        os.replace(temporary, directory / "batch_index.json")
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _saved(output_dir: Path, video_id: str, index: dict[str, dict[str, str]]) -> bool:
    entry = index.get(video_id, {})
    filename = entry.get("filename", f"{video_id}.txt")
    path = output_dir / filename
    if path.is_file() and bool(path.read_bytes().strip()):
        return True
    legacy = output_dir / f"{video_id}.txt"
    if legacy.is_file() and bool(legacy.read_bytes().strip()):
        return True
    organized_legacy = output_dir / "transcripts" / f"{video_id}.txt"
    return organized_legacy.is_file() and bool(organized_legacy.read_bytes().strip())


def _load_titles(titles_file: Path | None) -> dict[str, str]:
    if titles_file is None:
        return {}
    titles = {}
    for number, raw in enumerate(Path(titles_file).read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        fields = raw.split("\t") if "\t" in raw else raw.split("\\t")
        if len(fields) < 2 or not fields[1].strip():
            raise ValueError(f"Missing title at line {number} of {titles_file}")
        video_id = extract_video_id(fields[0].strip())
        titles[video_id] = fields[1].strip()
    return titles


def _safe_stem(title: str) -> str:
    cleaned = "".join("∕" if char == "/" else " " if ord(char) < 32 else char for char in title)
    cleaned = cleaned.strip().strip(".") or "Untitled"
    while len(cleaned.encode("utf-8")) > 230:
        cleaned = cleaned[:-1]
    return cleaned.rstrip(" .") or "Untitled"


def _filename_for(output_dir: Path, video_id: str, title: str,
                  index: dict[str, dict[str, str]]) -> str:
    if video_id in index:
        return index[video_id]["filename"]
    stem = _safe_stem(title)
    candidate = f"transcripts/{stem} [{video_id}].txt"
    claimed = {entry["filename"] for entry in index.values()}
    if candidate in claimed or (output_dir / candidate).exists():
        raise FileExistsError(f"No safe filename available for {video_id}: {candidate}")
    return candidate


def _resolve_title(video_id: str, titles: dict[str, str]) -> str:
    if video_id in titles:
        return titles[video_id]
    from videocontext.extractors.metadata import fetch_metadata
    try:
        title = fetch_metadata(video_id).title.strip()
    except Exception as error:
        if _is_rate_limited(error):
            raise RateLimitedError(f"YouTube metadata rate limit reached for {video_id}") from error
        raise RuntimeError(f"Could not retrieve title for {video_id}: {error}") from error
    if not title or title == "Unknown":
        raise RuntimeError(f"No video title available for {video_id}")
    return title


def inspect_batch(ids_file: Path, output_dir: Path) -> BatchStatus:
    """Show progress without making requests or changing output files."""
    videos = _load_video_ids(Path(ids_file))
    index = _load_index(Path(output_dir))
    saved = sum(_saved(Path(output_dir), video_id, index) for video_id in videos)
    return BatchStatus(total=len(videos), saved=saved, pending=len(videos) - saved)


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=path.parent,
            prefix=f".{path.name}.", suffix=".tmp", delete=False,
        ) as handle:
            temporary = Path(handle.name)
            handle.write(content)
        os.replace(temporary, path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _write_catalog(output_dir: Path, videos: list[str], titles: dict[str, str],
                   index: dict[str, dict[str, str]]) -> None:
    catalog = output_dir / "CATALOG.md"
    if catalog.exists() and not catalog.read_text(encoding="utf-8").startswith(CATALOG_MARKER):
        raise FileExistsError(f"Refusing to overwrite user-authored catalog: {catalog}")
    saved = sum(_saved(output_dir, video_id, index) for video_id in videos)
    lines = [
        CATALOG_MARKER, "# Video transcript catalog", "",
        f"**{saved} saved · {len(videos) - saved} pending · {len(videos)} total**", "",
        "Transcript text is in `transcripts/`. Source lists and the resume index are in `metadata/`; download logs are in `logs/`.",
        "Search this page by title or YouTube ID. Rerun `vc batch-transcripts` with `metadata/video_ids.txt` to resume.",
        "", "| Status | Video | YouTube ID |", "| --- | --- | --- |",
    ]
    for video_id in sorted(videos, key=lambda item: (titles.get(item) or index.get(item, {}).get("title") or item).casefold()):
        title = titles.get(video_id) or index.get(video_id, {}).get("title") or video_id
        label = title.replace("\\", "\\\\").replace("|", "\\|").replace("[", "\\[").replace("]", "\\]")
        entry = index.get(video_id, {})
        if _saved(output_dir, video_id, index) and entry.get("filename"):
            link = quote(entry["filename"], safe="/")
            video = f"[{label}]({link})"
            status = "Saved"
        else:
            video = label
            status = "Pending"
        lines.append(f"| {status} | {video} | `{video_id}` |")
    _write_text(catalog, "\n".join(lines) + "\n")


def organize_collection(ids_file: Path, output_dir: Path,
                        titles_file: Path | None = None) -> int:
    """Create the collection layout and migrate known files without network calls."""
    output_dir = Path(output_dir)
    videos = _load_video_ids(Path(ids_file))
    catalog = output_dir / "CATALOG.md"
    if catalog.exists() and not catalog.read_text(encoding="utf-8").startswith(CATALOG_MARKER):
        raise FileExistsError(f"Refusing to overwrite user-authored catalog: {catalog}")
    canonical_titles = output_dir / "metadata" / "video_titles.tsv"
    source_titles = Path(titles_file) if titles_file is not None else canonical_titles
    titles = _load_titles(source_titles) if source_titles.exists() else {}
    index = _load_index(output_dir)
    for directory in ("transcripts", "metadata", "logs"):
        (output_dir / directory).mkdir(parents=True, exist_ok=True)

    moved = 0
    for video_id in videos:
        entry = index.get(video_id, {})
        title = titles.get(video_id) or entry.get("title")
        candidates = []
        if entry.get("filename"):
            candidates.append(output_dir / entry["filename"])
        candidates.extend((output_dir / f"{video_id}.txt", output_dir / "transcripts" / f"{video_id}.txt"))
        if title:
            filename = f"transcripts/{_safe_stem(title)} [{video_id}].txt"
            candidates.append(output_dir / Path(filename).name)
            candidates.append(output_dir / filename)
        existing = next((path for path in candidates if path.is_file() and path.read_bytes().strip()), None)
        if existing is None:
            continue
        if not title:
            raise ValueError(f"No title available for saved video {video_id}; supply --titles-file")
        target = output_dir / filename
        if existing != target:
            if target.exists():
                raise FileExistsError(f"Refusing to overwrite {target}")
            existing.rename(target)
            moved += 1
        new_entry = {"title": title, "filename": filename}
        if index.get(video_id) != new_entry:
            index[video_id] = new_entry
            _save_index(output_dir, index)

    _write_text(output_dir / "metadata" / "video_ids.txt", "".join(f"{video_id}\n" for video_id in videos))
    if titles_file is not None:
        _write_text(canonical_titles, "".join(f"{video_id}\t{titles[video_id]}\n" for video_id in videos if video_id in titles))
    legacy_titles = output_dir / "_video_titles.tsv"
    if legacy_titles.exists() and legacy_titles != canonical_titles:
        target = output_dir / "metadata" / "legacy_video_titles.tsv"
        if not target.exists():
            legacy_titles.rename(target)
    legacy_index = output_dir / "_batch_index.json"
    if legacy_index.exists() and (output_dir / "metadata" / "batch_index.json").exists():
        target = output_dir / "metadata" / "legacy_batch_index.json"
        if not target.exists():
            legacy_index.rename(target)
    for old_name, new_name in (
        ("_batch_run.log", "batch_run.log"), ("_batch_failures.jsonl", "batch_failures.jsonl"),
        ("_fail.log", "legacy_fail.log"), ("_ok.log", "legacy_ok.log"),
        ("_vc.log", "legacy_vc.log"),
    ):
        source = output_dir / old_name
        target = output_dir / "logs" / new_name
        if source.exists() and not target.exists():
            source.rename(target)
    _write_catalog(output_dir, videos, titles, index)
    return moved


def migrate_existing(ids_file: Path, output_dir: Path, titles_file: Path) -> int:
    """Backward-compatible name for offline collection organization."""
    return organize_collection(ids_file, output_dir, titles_file)


def _write_transcript(output_dir: Path, video_id: str, filename: str,
                      segments: list[TranscriptSegment]) -> None:
    target = output_dir / filename
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=target.parent,
            prefix=f".{video_id}.", suffix=".tmp", delete=False,
        ) as handle:
            temporary = Path(handle.name)
            handle.write("\n".join(segment.text for segment in segments) + "\n")
        os.replace(temporary, target)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _record_failure(output_dir: Path, video_id: str, error: RuntimeError) -> None:
    record = {
        "video_id": video_id,
        "time": datetime.now(timezone.utc).isoformat(),
        "error": str(error),
    }
    directory = output_dir / "logs"
    directory.mkdir(parents=True, exist_ok=True)
    with (directory / "batch_failures.jsonl").open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, ensure_ascii=False) + "\n")


def download_transcripts(
    ids_file: Path,
    output_dir: Path,
    *,
    lang: str = "en",
    interval: float = 120,
    initial_cooldown: float = 1800,
    max_cooldown: float = 7200,
    max_rate_retries: int | None = 6,
    fetcher: Callable[[str, str], list[TranscriptSegment]] | None = None,
    sleeper: Callable[[float], None] | None = None,
    progress: Callable[[str], None] | None = None,
    titles_file: Path | None = None,
) -> BatchSummary:
    """Process any length list sequentially and resume from nonempty output files.

    `max_rate_retries=None` keeps waiting for a block to clear until interrupted.
    """
    if interval < 0 or initial_cooldown <= 0 or max_cooldown < initial_cooldown:
        raise ValueError("Interval must be nonnegative and cooldown bounds must be positive and ordered")
    if max_rate_retries is not None and max_rate_retries < 0:
        raise ValueError("max_rate_retries must be nonnegative or None")

    videos = _load_video_ids(Path(ids_file))
    output_dir = Path(output_dir)
    organize_collection(ids_file, output_dir, titles_file)
    canonical_titles = output_dir / "metadata" / "video_titles.tsv"
    titles = _load_titles(canonical_titles) if canonical_titles.exists() else {}
    transcript_index = _load_index(output_dir)
    pending = [video_id for video_id in videos if not _saved(output_dir, video_id, transcript_index)]
    fetch = fetcher or fetch_transcript
    sleep = sleeper or time.sleep
    report = progress or (lambda _: None)
    completed = failed = rate_limit_retries = 0
    skipped = len(videos) - len(pending)

    def summary() -> BatchSummary:
        return BatchSummary(len(videos), completed, skipped, failed, rate_limit_retries)

    for index, video_id in enumerate(pending, start=1):
        retries = 0
        title = titles.get(video_id)
        while True:
            try:
                if title is None:
                    title = _resolve_title(video_id, titles)
                segments = fetch(video_id, lang)
                if not any(segment.text.strip() for segment in segments):
                    raise RuntimeError("Transcript contained no text")
            except RateLimitedError as error:
                if max_rate_retries is not None and retries >= max_rate_retries:
                    report(f"PAUSED {video_id}: {error}")
                    raise BatchPaused(video_id, retries, summary()) from error
                wait = min(initial_cooldown * (2 ** retries), max_cooldown)
                if error.retry_after is not None:
                    wait = max(wait, error.retry_after)
                retries += 1
                rate_limit_retries += 1
                report(f"RATE LIMITED {video_id}; waiting {wait:g}s before retry {retries}")
                sleep(wait)
                continue
            except RuntimeError as error:
                _record_failure(output_dir, video_id, error)
                failed += 1
                report(f"FAILED {video_id}: {error}")
            else:
                filename = _filename_for(output_dir, video_id, title, transcript_index)
                transcript_index[video_id] = {"title": title, "filename": filename}
                _save_index(output_dir, transcript_index)
                _write_transcript(output_dir, video_id, filename, segments)
                if video_id not in titles:
                    titles[video_id] = title
                    _write_text(canonical_titles, "".join(
                        f"{item}\t{titles[item]}\n" for item in videos if item in titles
                    ))
                _write_catalog(output_dir, videos, titles, transcript_index)
                completed += 1
                report(f"SAVED {video_id} ({index}/{len(pending)} pending this run)")
            break
        if index < len(pending):
            sleep(interval)

    return summary()
